Project: rename `commit-msgconv`, add global `.gitignore`

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -4,8 +4,8 @@
 # Precommit message validation to conform to the standard 'Title (opt): message'
 # specification.
 #
-# Copy commit-msgconv to .git/hooks/:
-#   cp commit-msgconv .git/hooks/commit-msg
+# Copy this file to your local repository:
+#   cp commit-msg .git/hooks/
 #
 # Foo: bar roo
 # Foo (bar): roo
@@ -19,6 +19,6 @@ commit_msg=$(grep -v '^#\|^$' "$1")
 if echo "$commit_msg" | egrep '^[A-Z0-9].*:\s.+' > /dev/null; then
     exit 0
 else
-    echo >&2 "hooks/commit-msgconv: not conforming to 'Title (opt)?: message' spec; aborted"
+    echo >&2 "hooks/commit-msg: not conforming to 'Title (opt)?: message' spec; aborted"
     exit 1
 fi
